---
namespace: infra
name: aap_configuration
version: 3.8.3-devel
description: A collection of roles to manage Ansible Controller
readme: README.md
authors:
  - Andrew Huffman
  - Adebisi Oyawale @aoyawale
  - Kedar Kulkarni @kedark3
  - Tom Page @Tompage1994
  - Sean Sullivan @sean-m-sullivan
  - David Danielsson @djdanielsson
  - Brant Evans @branic
repository: https://github.com/redhat-cop/infra.aap_configuration
issues: https://github.com/redhat-cop/infra.aap_configuration/issues
build_ignore:
  - galaxy.yml.j2
  - release.yml
  - .github
  - "*.tar.gz"
  - tests/*
license:
  - GPL-3.0-or-later
tags:
  - controller
  - collection
  - controller_configuration
  - automation_platform
  - infrastructure
dependencies:
  "ansible.platform": ">=2.5.0"
  "ansible.hub": ">=1.0.0"
  "ansible.controller": ">=4.6.0"
  "ansible.eda": ">=2.5.0"
...
